#!/usr/bin/env bash

# Colors for 'echo' command
GREEN='\033[1;32m'
RED='\033[1;31m'
NC='\033[0m' # No Color

function main() {
	if [ "$#" -ne 2 ]; then
		echo '  Usage: usbdd IF OF'
		echo 'Writes iso image from IF (INFILE) to OF (OUTFILE) and sync it.'
		echo '  Example: "usbdd ./foo.iso /dev/foo"'
		return
	fi

	args=( "$@" )
	pathFrom=${args[0]}
	pathTo=${args[1]}

	startTime=$SECONDS

	# https://www.linuxquestions.org/questions/slackware-14/dd-and-status=progress-4175581355/
	# TLDR; It avoids hanging `dd` command
	echo "0. Obtaining ${pathTo} optimal I/O size..."

	optimalIOSize=$(sudo fdisk -l "$pathTo" | grep "I/O size (minimum/optimal):" | grep -Eo "[0-9]+" | tail -n1)
	echo "${pathTo} optimal I/O size: $optimalIOSize"

	echo '1. Running dd...'

	dd bs="$optimalIOSize" if="$pathFrom" of="$pathTo" status=progress 2>&1 | tee dd.err

	# check any errors
	ddErr=$( cat dd.err )
	if [[ "$ddErr" == *'dd:'* ]]; then
		if [[ "$ddErr" == *'Permission denied'* ]]; then
			echo "Try run it with sudo:"
			echo -e "  ${GREEN}sudo usbdd $pathFrom $pathTo${NC}"
		fi
		echo -e "${RED}Quiting...${NC}" >&2
		return
	fi
	rm -f ./dd.err

	echo '2. Syncing...'

	sync &
	pID=$!;
	killErr=""

	while [ "$killErr" = "" ]; do
		killErr=$(kill -0 "$pID" 2>&1 > /dev/null)
		cacheInfo=$(grep -E '(Dirty|Writeback):' /proc/meminfo)

		echo "$cacheInfo"
		sleep 0.5

		clearLastLines 2
	done

	echo "$cacheInfo"

	elapsedTime=$(( SECONDS - startTime ))
	echo 'Finished in:'
	date -ud "@$elapsedTime" +'%H hr %M min %S sec'
	echo -e "${GREEN}ISO image written successfully!${NC}"
}

# https://stackoverflow.com/a/78015981
function clearLastLines() {
	local linesToClear=$1

	for (( i=0; i<linesToClear; i++ )); do
		tput cuu 1
		tput el
	done
}

main "$@"; exit
