#!/usr/bin/env bash

# Colors for 'echo' command
GREEN='\033[1;32m'
NC='\033[0m' # No Color

function main() {
	if [ "$#" -ne 1 ]; then
		echo '  Usage: usbumount SRC | DIR'
		echo 'Sync and unmount SRC or DIR.'
		return
	fi

	args=( "$@" )
	pathToUmount=${args[0]}

	echo "${pathToUmount}"

	startTime=$SECONDS

	echo '1. Syncing...'

	sync &
	pID=$!;
	killErr=""

	while [ "$killErr" = "" ]; do
		killErr=$(kill -0 "$pID" 2>&1 > /dev/null)
		cacheInfo=$(grep -E '(Dirty|Writeback):' /proc/meminfo)

		echo "$cacheInfo"
		sleep 0.5

		clearLastLines 2
	done

	echo "$cacheInfo"

	echo '2. Unmounting...'
	umount "$pathToUmount"

	elapsedTime=$(( SECONDS - startTime ))
	echo 'Finished in:'
	date -ud "@$elapsedTime" +'%H hr %M min %S sec'
	echo -e "${GREEN}Umounted successfully!${NC}"
}

# https://stackoverflow.com/a/78015981
function clearLastLines() {
	local linesToClear=$1

	for (( i=0; i<linesToClear; i++ )); do
		tput cuu 1
		tput el
	done
}

main "$@"; exit
